[project]
name = "stacks-sip"
description = "Systematic Investment Plan on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.sip-contract]
path = "contracts/sip-contract.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false